# Generated by Django 2.0.2 on 2019-12-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
